default_tech_settings:
  comfyui_config:
    server_address: "192.168.1.10:8188"
    client_id: "my_client"
  workflow_config:
    workflow_json_path: "/path/to/workflow.json"
    image_output_path: "/path/to/output"
    library_file_path: "/path/to/library.yaml"
    seed_node_id: 164
    batch_size_node_id: 22
    negative_prompt_node_id: 174
    positive_prompt_node_id: 257
    environment_prompt_node_id: 303
    default_prompts:
      base_positive_prompt: "masterpiece, best quality"
      negative_prompt: "lowres, bad anatomy"
      batch_size: 4

scenes:
  - name: "studying"
    display_name: "勉強しているシーン"
    positive_prompt: "sitting at desk, studying"
    negative_prompt: "blurry"
    batch_size: 2
    preview_image: "scenes/studying.png"
  - name: "sleeping"
    display_name: "寝ているシーン"
    positive_prompt: "lying in bed"

environments:
  - name: "indoor"
    display_name: "室内"
    environment_prompt: "indoor room, soft lighting"
    thumbnail: "thumbnails/indoor.jpg"
  - name: "outdoor"
    display_name: "屋外"
    environment_prompt: "outdoor, sunny"